### ISSUE TITLE
java.lang.IllegalArgumentException: <N> is not a valid line for pointer

### ISSUE THREAD

**Issue by svaccari** [StevenLooman/magik-tools#14] opened 2022-10-27 14:21 UTC
Hi,

I used [version 0.5.2](https://github.com/StevenLooman/magik-tools/releases/download/0.5.2/sonar-magik-plugin-0.5.2.jar) in Sonarqube from command line with sonar-scanner:

<pre>
SonarScanner 4.7.0.2747
INFO: Java 11.0.14.1 Eclipse Adoptium (64-bit)
INFO: Linux 5.14.0-1052-oem amd64
</pre>

Input consists of 4 Magik files. Depending on **file analysis order**, I receive the following exception:

<pre>
INFO: Sensor Magik Squid Sensor [magik]
INFO: 4 source files to be analyzed
INFO: 1/4 files analyzed, current file: test/bi_utilities.magik
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 8.268s
INFO: 2/4 files analyzed, current file: test/unit_test.magik
INFO: Final Memory: 17M/88M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarScanner execution
java.lang.IllegalArgumentException: 79 is not a valid line for pointer. File test/unit_test.magik has 74 line(s)
	at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:348)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:284)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.selectLine(DefaultInputFile.java:307)
	at nl.ramsolutions.sw.sonar.sensors.MagikSquidSensor.saveIssues(MagikSquidSensor.java:197)
	at nl.ramsolutions.sw.sonar.sensors.MagikSquidSensor.scanMagikFile(MagikSquidSensor.java:127)
	at nl.ramsolutions.sw.sonar.sensors.MagikSquidSensor.execute(MagikSquidSensor.java:98)
</pre>

### Test 1

1. 250 rows
2. 7209 rows
3. 74 rows -> EXCEPTION

### Test 2

1. 7209 rows
2. 74 rows -> EXCEPTION

### Test 3

1. 250 rows
2. 74 rows -> EXCEPTION

### Test 4

1. 74 rows
2. 7209 rows 
3. 250 rows -> SUCCESS

It seems that the Magik plugin maintains some state that is later used in a shorter file, causing the error.
Let me know if you need other information.

Thanks!

**Comment by StevenLooman** [comment] 2022-10-30 16:57
Thank you for this issue @svaccari. I hope to take a look at this very soon! I'll let you know if I need more information.

**Comment by StevenLooman** [comment] 2022-11-04 15:31
I've release 0.5.3 which includes a fix for this problem.

Again, thank you for reporting it. Please let me know if you find any other issues. Please also be aware that the SonarQube plugin is given less attention compared to the linter and the language server/debug adapter. I think those tools will be more effective during development as these provide direct feedback instead of given feedback after committing/pushing (assuming you are using something like git for version control).

**Closed** 2022-11-04 16:27 UTC

**Comment by StevenLooman** [comment] 2022-11-05 09:35
> About that, are you able to debug code with SW 5.x? As in putting breakpoints and inspecting variables... Which tool are you using in that case?

I see that I forgot to upload the vscode extension with this release. I am using vscode myself. Through this I can use the language server functionality and debug functionality. Through the debug functionality I can set breakpoints and inspect variables indeed. Though, the debug interface provided by SW5 does have its limitations. I expect it is a bit unstable, though this can be caused by magik-tools as well of course. The other downside is the SW5 debug interface does not handle loops at all. I.e., you can set a breakpoint in a loop and inspect the variables of that frame, but it does not provide information about where it is in the source. When hitting a breakpoint that is ok'ish, but when stepping through code things become a bit rough.

Others are using emacs + [lsp-mode](https://emacs-lsp.github.io/lsp-mode/). There is a [dap-mode](https://emacs-lsp.github.io/dap-mode/) as well, but there is no "official" magik support. Yet, I am working on this...


Also, I'm working on some larget changes to the language server. These are not visible on Github but I hope to release those soon.
